### ISSUE TITLE
Check python3 version is correct

### ISSUE THREAD

**Issue by nirlipo** [AI4EDUC/pacman-contest-3#10]
I found a diff from this repo over here:

https://github.com/nirlipo/COMP90054-lectures/blob/master/Assignments/pacman-github-template-python3/

see for example lines 
https://github.com/nirlipo/COMP90054-lectures/blob/master/Assignments/pacman-github-template-python3/pacman-contest/util.py#L311

and 

https://github.com/nirlipo/COMP90054-lectures/blob/master/Assignments/pacman-github-template-python3/pacman-contest/util.py#L313

compared to this version in https://github.com/AI4EDUC/pacman-contest-3/blob/master/util.py#L310

I'd recommend merging the version above unless you did other changes

**Comment by ssardina** [comment]
Ouch, this is painful, but glad you checked it... Yes, I did _many_ improvements in the last couple of days that I don't want to re-do.

I will see if I can push the offline version in your repo into a branch and see how a merge goes.

But I would recommend to always do changes in our repos and not offline, even if another branches if we are not sure. I guess this was done by a tutor? it happened to me in AI last year when another prof was running it and he did all the changes offline in his own machine!!

**Comment by ssardina** [comment]
Done, there wasn't much but better do it now or we will forget. See PR #13 for you to review and approve.

Thanks for catching this!

Also, we can work like this:

1. If it is really trivial changes and we are 100% sure it works, just you/me push to master (we are owners and we can, others will need reviews)
2. Otherwise, we request a review from each other. If the reviewer accepts, then he does the merging. OK? So, I requested a review for PR #13. If you accept, then YOU merge (always trying to do re-base + merge to keep linear history if possible).

If you want another workflow let me know.

**Comment by nirlipo** [comment]
Good, I'll follow the advice. I didn't rebase the PR. I will do the following ones :)

**Comment by ssardina** [comment]
Yes sometimes we won't be able to rebase (or is a lot of work not worth it) and we will just have to do standard merge, no problem
